# Generated by Django 3.0.8 on 2020-10-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoline',
            options={'ordering': ['id'], 'verbose_name': 'Linea de pedido', 'verbose_name_plural': 'Linea de pedidos'},
        ),
        migrations.AlterModelTable(
            name='pedidoline',
            table='orderlines',
        ),
    ]
