# Generated by Django 3.0.8 on 2020-07-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_Pedido', models.DateTimeField()),
                ('Fecha_de_Entrega', models.DateTimeField()),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dellepianes.Estado_Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_producto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('DNI', models.IntegerField()),
                ('Telefono', models.CharField(max_length=255)),
                ('Mail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Tipo_de_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dellepianes.Tipo_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dellepianes.Pedido')),
                ('Producto', models.ManyToManyField(blank=True, to='Dellepianes.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dellepianes.Usuario'),
        ),
    ]
