# Generated by Django 3.0.8 on 2020-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_detalle',
            name='Cantidad',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
