# Generated by Django 3.0.8 on 2020-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0003_auto_20200729_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodetalle',
            name='DNI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariodetalle',
            name='Mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuariodetalle',
            name='Telefono',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
