# Generated by Django 3.0.8 on 2020-09-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0004_auto_20200730_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
