# Generated by Django 3.0.8 on 2020-09-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dellepianes.Producto')),
            ],
        ),
    ]
