# Generated by Django 3.0.8 on 2020-09-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0006_auto_20200920_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Imagen',
        ),
    ]
