# Generated by Django 3.0.8 on 2020-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0007_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
