# Generated by Django 3.0.8 on 2020-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0008_auto_20200925_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
