# Generated by Django 3.0.8 on 2020-10-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0009_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(),
        ),
    ]
