# Generated by Django 3.0.8 on 2020-10-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dellepianes', '0010_auto_20201014_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='pedido_detalle',
            name='Pedido',
        ),
        migrations.RemoveField(
            model_name='pedido_detalle',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Estado_Pedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Pedido_Detalle',
        ),
    ]
